title: 3rdlab
email: getthecore@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://3rdlab.github.io 
github_username:  3rdlab

# Build settings
markdown: kramdown
# theme: minima
# theme: jekyll-theme-minimal
# remote_theme : mmistakes/minimal-mistakes
remote_theme : chesterhow/tale
permalink:    /:year-:month-:day/:title
paginate:     5<Paste>

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme


# custom setting
disqus:
  shortname: 3rdlab

google_analytics: UA-64053570-2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
