title: 3rdlab
email: getthecore@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://3rdlab.github.io 
# twitter_username: jekyllrb
github_username:  3rdlab

# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# custom setting
disqus:
  shortname: 3rdlab

google_analytics: UA-64053570-2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
